import type { BlockDefault } from "@/hooks/use-page-blocks";

export const PAGE_IDS = {
  home: 1,
  menu: 2,
  "carta-vini": 3,
  "cocktail-bar": 4,
  eventi: 5,
  "eventi-privati": 6,
  galleria: 7,
  "dove-siamo": 8,
  "eventi-privati-aperitivo": 9,
  "eventi-privati-cena": 10,
  "eventi-privati-esclusivo": 11,
} as const;

export const MENU_DEFAULTS: BlockDefault[] = [
  {
    blockType: "hero",
    titleIt: "Menù",
    titleEn: "Menu",
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 0,
  },
  {
    blockType: "intro",
    bodyIt: "La nostra cucina celebra i sapori autentici della tradizione italiana, reinterpretati con creatività e ingredienti di stagione.",
    bodyEn: "Our cuisine celebrates the authentic flavors of Italian tradition, reinterpreted with creativity and seasonal ingredients.",
    bodyFontSize: 20,
    bodyFontSizeMobile: 14,
    sortOrder: 1,
  },
];

export const CARTA_VINI_DEFAULTS: BlockDefault[] = [
  {
    blockType: "hero",
    titleIt: "Carta dei Vini",
    titleEn: "Wine List",
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 0,
  },
  {
    blockType: "intro",
    bodyIt: "Una selezione curata di etichette italiane e internazionali, scelte per accompagnare ogni momento della vostra esperienza.",
    bodyEn: "A curated selection of Italian and international labels, chosen to accompany every moment of your experience.",
    bodyFontSize: 20,
    bodyFontSizeMobile: 14,
    sortOrder: 1,
  },
];

export const COCKTAIL_BAR_DEFAULTS: BlockDefault[] = [
  {
    blockType: "hero",
    titleIt: "Cocktail Bar",
    titleEn: "Cocktail Bar",
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 0,
  },
  {
    blockType: "intro",
    bodyIt: "I nostri cocktail sono creazioni uniche, preparate con ingredienti selezionati e tecniche innovative per offrirvi un'esperienza sensoriale indimenticabile.",
    bodyEn: "Our cocktails are unique creations, prepared with selected ingredients and innovative techniques to offer you an unforgettable sensory experience.",
    bodyFontSize: 20,
    bodyFontSizeMobile: 14,
    sortOrder: 1,
  },
  {
    blockType: "gallery-1",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 2,
  },
  {
    blockType: "gallery-2",
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 3,
  },
  {
    blockType: "gallery-3",
    imageUrl: "https://images.unsplash.com/photo-1560963689-b5682b6440f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 4,
  },
  {
    blockType: "outro",
    bodyIt: "Oltre alla nostra selezione di cocktail, il bar offre grandi classici internazionali, una scelta di whisky, rum e spirits, più birre e altre referenze.",
    bodyEn: "In addition to our cocktail selection, the bar offers great international classics, a curated selection of whiskies, rums and spirits, plus beers and other offerings.",
    bodyFontSize: 16,
    bodyFontSizeMobile: 14,
    sortOrder: 5,
  },
];

export const EVENTI_DEFAULTS: BlockDefault[] = [
  {
    blockType: "hero",
    titleIt: "Eventi",
    titleEn: "Events",
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 0,
  },
  {
    blockType: "intro",
    bodyIt: "Scopri i nostri eventi speciali: serate a tema, degustazioni, musica dal vivo e molto altro.",
    bodyEn: "Discover our special events: themed nights, tastings, live music and much more.",
    bodyFontSize: 20,
    bodyFontSizeMobile: 14,
    sortOrder: 1,
  },
];

export const EVENTI_PRIVATI_DEFAULTS: BlockDefault[] = [
  {
    blockType: "hero",
    titleIt: "Eventi Privati",
    titleEn: "Private Events",
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    imageUrl: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 0,
  },
  {
    blockType: "intro",
    bodyIt: "Camera con Vista offre spazi esclusivi e servizi personalizzati per rendere ogni occasione indimenticabile. Dal party aziendale alla celebrazione privata, ogni dettaglio è curato con la massima attenzione.",
    bodyEn: "Camera con Vista offers exclusive spaces and personalized services to make every occasion unforgettable. From corporate parties to private celebrations, every detail is curated with the utmost attention.",
    bodyFontSize: 20,
    bodyFontSizeMobile: 14,
    sortOrder: 1,
  },
  {
    blockType: "section-title",
    titleIt: "Il tuo evento, la nostra passione",
    titleEn: "Your event, our passion",
    titleFontSize: 36,
    titleFontSizeMobile: 28,
    sortOrder: 2,
  },
  {
    blockType: "package-1",
    titleIt: "Aperitivo Esclusivo",
    titleEn: "Exclusive Aperitivo",
    titleFontSize: 20,
    titleFontSizeMobile: 18,
    bodyIt: "Cocktail personalizzati e finger food selezionati per i tuoi ospiti. Ideale per 20-50 persone.",
    bodyEn: "Personalized cocktails and selected finger food for your guests. Ideal for 20-50 people.",
    bodyFontSize: 14,
    bodyFontSizeMobile: 13,
    sortOrder: 3,
  },
  {
    blockType: "package-2",
    titleIt: "Cena Privata",
    titleEn: "Private Dinner",
    titleFontSize: 20,
    titleFontSizeMobile: 18,
    bodyIt: "Menu degustazione con abbinamento vini in sala riservata. Ideale per 10-30 persone.",
    bodyEn: "Tasting menu with wine pairing in a private room. Ideal for 10-30 people.",
    bodyFontSize: 14,
    bodyFontSizeMobile: 13,
    sortOrder: 4,
  },
  {
    blockType: "package-3",
    titleIt: "Party & Celebrazioni",
    titleEn: "Parties & Celebrations",
    titleFontSize: 20,
    titleFontSizeMobile: 18,
    bodyIt: "Location completa con DJ, cocktail bar dedicato e catering. Ideale per 50-100 persone.",
    bodyEn: "Complete venue with DJ, dedicated cocktail bar and catering. Ideal for 50-100 people.",
    bodyFontSize: 14,
    bodyFontSizeMobile: 13,
    sortOrder: 5,
  },
  {
    blockType: "package-4",
    titleIt: "Experience Premium",
    titleEn: "Premium Experience",
    titleFontSize: 20,
    titleFontSizeMobile: 18,
    bodyIt: "Pacchetto su misura con mixology class e menu personalizzato. Per gruppi esclusivi.",
    bodyEn: "Tailored package with mixology class and personalized menu. For exclusive groups.",
    bodyFontSize: 14,
    bodyFontSizeMobile: 13,
    sortOrder: 6,
  },
  {
    blockType: "spaces-1",
    imageUrl: "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 7,
  },
  {
    blockType: "spaces-2",
    imageUrl: "https://images.unsplash.com/photo-1560624052-449f5ddf0c31?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 8,
  },
  {
    blockType: "spaces-3",
    imageUrl: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 9,
  },
  {
    blockType: "test-image",
    imageUrl: "",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 10,
  },
  {
    blockType: "cta",
    titleIt: "Richiedi un preventivo",
    titleEn: "Request a Quote",
    titleFontSize: 32,
    titleFontSizeMobile: 24,
    bodyIt: "Contattaci per discutere le tue esigenze e creare insieme l'evento perfetto.",
    bodyEn: "Contact us to discuss your needs and create the perfect event together.",
    bodyFontSize: 18,
    bodyFontSizeMobile: 14,
    sortOrder: 11,
  },
  {
    blockType: "spaces-title",
    titleIt: "I nostri spazi",
    titleEn: "Our Spaces",
    titleFontSize: 32,
    titleFontSizeMobile: 24,
    sortOrder: 12,
  },
];

export const APERITIVO_PAGE_DEFAULTS: BlockDefault[] = [
  {
    blockType: "hero",
    titleIt: "Aperitivo Privato",
    titleEn: "Private Aperitivo",
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    imageUrl: "",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 0,
  },
  {
    blockType: "intro",
    bodyIt: "Cocktail personalizzati e finger food selezionati per i tuoi ospiti, in un'atmosfera elegante e riservata.",
    bodyEn: "Personalized cocktails and selected finger food for your guests, in an elegant and private atmosphere.",
    bodyFontSize: 20,
    bodyFontSizeMobile: 14,
    sortOrder: 1,
  },
  {
    blockType: "section-a",
    titleIt: "Fino a 25/30 persone",
    titleEn: "Up to 25/30 guests",
    titleFontSize: 24,
    titleFontSizeMobile: 20,
    bodyIt: "Sala 1 riservata in esclusiva.\nMenu dedicato a base di finger food.\n\nMinimum spending:\n• Lunedì–Giovedì: 1.000€\n• Venerdì–Sabato: 1.500€",
    bodyEn: "Sala 1 exclusively reserved.\nDedicated finger food menu.\n\nMinimum spending:\n• Monday–Thursday: €1,000\n• Friday–Saturday: €1,500",
    bodyFontSize: 16,
    bodyFontSizeMobile: 14,
    sortOrder: 2,
  },
  {
    blockType: "section-b",
    titleIt: "Da 30 a 80 persone",
    titleEn: "From 30 to 80 guests",
    titleFontSize: 24,
    titleFontSizeMobile: 20,
    bodyIt: "Sala 1 e Sala 2 riservate.\nMenu dedicato a base di finger food.\n\nMinimum spending:\n• Lunedì–Giovedì: 1.000€\n• Venerdì–Sabato: 1.500€",
    bodyEn: "Sala 1 and Sala 2 reserved.\nDedicated finger food menu.\n\nMinimum spending:\n• Monday–Thursday: €1,000\n• Friday–Saturday: €1,500",
    bodyFontSize: 16,
    bodyFontSizeMobile: 14,
    sortOrder: 3,
  },
  {
    blockType: "gallery-1",
    imageUrl: "",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 4,
  },
  {
    blockType: "gallery-2",
    imageUrl: "",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 5,
  },
  {
    blockType: "cta",
    titleIt: "Richiedi un preventivo",
    titleEn: "Request a Quote",
    titleFontSize: 28,
    titleFontSizeMobile: 24,
    bodyIt: "Contattaci per organizzare il tuo aperitivo privato.",
    bodyEn: "Contact us to organize your private aperitivo.",
    bodyFontSize: 18,
    bodyFontSizeMobile: 14,
    sortOrder: 6,
  },
];

export const CENA_PAGE_DEFAULTS: BlockDefault[] = [
  {
    blockType: "hero",
    titleIt: "Cena Privata",
    titleEn: "Private Dinner",
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    imageUrl: "",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 0,
  },
  {
    blockType: "intro",
    bodyIt: "Una cena classica a sedere, con tavoli riservati e un servizio dedicato per il vostro gruppo.",
    bodyEn: "A classic seated dinner, with reserved tables and dedicated service for your group.",
    bodyFontSize: 20,
    bodyFontSizeMobile: 14,
    sortOrder: 1,
  },
  {
    blockType: "section-a",
    titleIt: "La vostra cena",
    titleEn: "Your dinner",
    titleFontSize: 24,
    titleFontSizeMobile: 20,
    bodyIt: "Tavoli riservati in base al numero di ospiti.\nMenu e pacchetti dedicati in fase di definizione.",
    bodyEn: "Tables reserved based on the number of guests.\nDedicated menus and packages coming soon.",
    bodyFontSize: 16,
    bodyFontSizeMobile: 14,
    sortOrder: 2,
  },
  {
    blockType: "gallery-1",
    imageUrl: "",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 3,
  },
  {
    blockType: "gallery-2",
    imageUrl: "",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 4,
  },
  {
    blockType: "cta",
    titleIt: "Richiedi un preventivo",
    titleEn: "Request a Quote",
    titleFontSize: 28,
    titleFontSizeMobile: 24,
    bodyIt: "Contattaci per organizzare la tua cena privata.",
    bodyEn: "Contact us to organize your private dinner.",
    bodyFontSize: 18,
    bodyFontSizeMobile: 14,
    sortOrder: 5,
  },
];

export const ESCLUSIVO_PAGE_DEFAULTS: BlockDefault[] = [
  {
    blockType: "hero",
    titleIt: "Evento Privato Esclusivo",
    titleEn: "Exclusive Private Event",
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    imageUrl: "",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 0,
  },
  {
    blockType: "intro",
    bodyIt: "Scegli la formula esclusiva più adatta al tuo evento. Sale riservate o l'intero locale, per un'esperienza senza compromessi.",
    bodyEn: "Choose the exclusive formula that best suits your event. Private rooms or the entire venue, for an uncompromising experience.",
    bodyFontSize: 20,
    bodyFontSizeMobile: 14,
    sortOrder: 1,
  },
  {
    blockType: "option-convivialis",
    titleIt: "Tavolo Convivialis",
    titleEn: "Convivialis Table",
    titleFontSize: 22,
    titleFontSizeMobile: 18,
    bodyIt: "Cena esclusiva al grande tavolo conviviale, con la sala riservata.\n\nMinimum spending:\n• Lunedì–Giovedì: 1.000€\n• Venerdì–Sabato: 1.500€",
    bodyEn: "Exclusive dinner at the large communal table, with a private room.\n\nMinimum spending:\n• Monday–Thursday: €1,000\n• Friday–Saturday: €1,500",
    bodyFontSize: 15,
    bodyFontSizeMobile: 13,
    sortOrder: 2,
  },
  {
    blockType: "option-riserva-ccv",
    titleIt: "Riserva Camera con Vista",
    titleEn: "Reserve Camera con Vista",
    titleFontSize: 22,
    titleFontSizeMobile: 18,
    bodyIt: "Riserva l'intero Bistrot Camera con Vista per il tuo evento.\nParty con DJ set, cocktail bar dedicato, menu personalizzato.\n\nTrattative riservate a partire da 4.000€",
    bodyEn: "Reserve the entire Camera con Vista Bistrot for your event.\nParty with DJ set, dedicated cocktail bar, custom menu.\n\nPrivate negotiations starting from €4,000",
    bodyFontSize: 15,
    bodyFontSizeMobile: 13,
    sortOrder: 3,
  },
  {
    blockType: "option-riserva-jazz",
    titleIt: "Riserva Camera Jazz Club",
    titleEn: "Reserve Camera Jazz Club",
    titleFontSize: 22,
    titleFontSizeMobile: 18,
    bodyIt: "Riserva l'intero Camera Jazz Club per il tuo evento.\nParty con DJ set, cocktail bar dedicato, menu personalizzato.\n\nTrattative riservate a partire da 4.000€",
    bodyEn: "Reserve the entire Camera Jazz Club for your event.\nParty with DJ set, dedicated cocktail bar, custom menu.\n\nPrivate negotiations starting from €4,000",
    bodyFontSize: 15,
    bodyFontSizeMobile: 13,
    sortOrder: 4,
  },
  {
    blockType: "gallery-1",
    imageUrl: "",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 5,
  },
  {
    blockType: "gallery-2",
    imageUrl: "",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 6,
  },
  {
    blockType: "cta",
    titleIt: "Richiedi un preventivo",
    titleEn: "Request a Quote",
    titleFontSize: 28,
    titleFontSizeMobile: 24,
    bodyIt: "Contattaci per organizzare il tuo evento esclusivo.",
    bodyEn: "Contact us to organize your exclusive event.",
    bodyFontSize: 18,
    bodyFontSizeMobile: 14,
    sortOrder: 7,
  },
];

export const GALLERIA_DEFAULTS: BlockDefault[] = [
  {
    blockType: "hero",
    titleIt: "Galleria",
    titleEn: "Gallery",
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    imageUrl: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 0,
  },
  {
    blockType: "intro",
    bodyIt: "Scopri l'atmosfera unica di Camera con Vista attraverso i nostri album fotografici.",
    bodyEn: "Discover the unique atmosphere of Camera con Vista through our photo albums.",
    bodyFontSize: 20,
    bodyFontSizeMobile: 14,
    sortOrder: 1,
  },
];

export const DOVE_SIAMO_DEFAULTS: BlockDefault[] = [
  {
    blockType: "hero",
    titleIt: "Dove Siamo",
    titleEn: "Where We Are",
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    imageUrl: "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    sortOrder: 0,
  },
  {
    blockType: "intro",
    bodyIt: "Nel cuore di Bologna..\na 200 metri dalle Due Torri\nraggiungibile in 3 minuti a piedi.",
    bodyEn: "In the heart of Bologna..\n200 meters from the Two Towers\njust a 3-minute walk.",
    bodyFontSize: 20,
    bodyFontSizeMobile: 14,
    sortOrder: 1,
  },
];
