import type { TeaserSectionData } from "./TeaserSection";

export const HOME_PAGE_ID = 1;

export const DEFAULT_BLOCKS = {
  hero: {
    blockType: "hero",
    sortOrder: 0,
    titleIt: "Camera con Vista",
    titleEn: "Camera con Vista",
    bodyIt: "Ristorante & Cocktail Bar",
    bodyEn: "Restaurant & Cocktail Bar",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    bodyFontSize: 28,
    bodyFontSizeMobile: 20,
    isDraft: false,
  },
  concept: {
    blockType: "concept",
    sortOrder: 1,
    titleIt: "Il nostro concept",
    titleEn: "Our Concept",
    bodyIt: "Camera con Vista è riconosciuto come uno dei cocktail bar più rinomati di Bologna. La nostra filosofia si basa sulla qualità degli ingredienti, l'innovazione nelle tecniche e la passione per l'ospitalità.",
    bodyEn: "Camera con Vista is recognized as one of the most renowned cocktail bars in Bologna. Our philosophy is based on the quality of ingredients, innovation in techniques, and passion for hospitality.",
    titleFontSize: 36,
    titleFontSizeMobile: 28,
    bodyFontSize: 16,
    bodyFontSizeMobile: 14,
    isDraft: false,
  },
  branding: {
    blockType: "branding",
    sortOrder: 2,
    titleIt: "RESTAURANT & COCKTAIL BAR",
    titleEn: "RESTAURANT & COCKTAIL BAR",
    bodyIt: "French nuance, antique goods",
    bodyEn: "French nuance, antique goods",
    titleFontSize: 15,
    titleFontSizeMobile: 11,
    bodyFontSize: 26,
    bodyFontSizeMobile: 18,
    isDraft: false,
  },
};

export const TEASER_SECTIONS: TeaserSectionData[] = [
  {
    subtitleIt: "Ristorante",
    subtitleEn: "Restaurant",
    titleIt: "Il nostro Menù",
    titleEn: "Our Menu",
    bodyIt: "La nostra cucina celebra i sapori autentici della tradizione italiana, reinterpretati con creatività e ingredienti di stagione. Ogni piatto è un viaggio sensoriale tra gusto e raffinatezza.",
    bodyEn: "Our cuisine celebrates the authentic flavors of Italian tradition, reinterpreted with creativity and seasonal ingredients. Each dish is a sensory journey between taste and refinement.",
    ctaLabelIt: "Scopri il menù",
    ctaLabelEn: "Discover the menu",
    ctaHref: "/menu",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    testId: "teaser-menu",
  },
  {
    subtitleIt: "Carta dei Vini",
    subtitleEn: "Wine List",
    titleIt: "I nostri Vini",
    titleEn: "Our Wines",
    bodyIt: "Una selezione curata di etichette italiane e internazionali, scelte per accompagnare ogni momento della vostra esperienza. Dal calice alla bottiglia, ogni vino racconta il suo territorio.",
    bodyEn: "A curated selection of Italian and international labels, chosen to accompany every moment of your experience. From the glass to the bottle, each wine tells the story of its territory.",
    ctaLabelIt: "Esplora la carta",
    ctaLabelEn: "Explore the list",
    ctaHref: "/carta-vini",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    testId: "teaser-vini",
  },
  {
    subtitleIt: "Cocktail Bar",
    subtitleEn: "Cocktail Bar",
    titleIt: "I nostri Cocktail",
    titleEn: "Our Cocktails",
    bodyIt: "Cocktail creativi preparati con ingredienti di prima qualità dai nostri mixologist. Ogni creazione è pensata per sorprendere e deliziare, rispettando la tradizione mentre esplora nuovi orizzonti del gusto.",
    bodyEn: "Creative cocktails crafted with premium ingredients by our mixologists. Each creation is designed to surprise and delight, respecting tradition while exploring new horizons of taste.",
    ctaLabelIt: "Scopri i cocktail",
    ctaLabelEn: "Discover cocktails",
    ctaHref: "/cocktail-bar",
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    testId: "teaser-cocktail",
  },
  {
    subtitleIt: "Eventi",
    subtitleEn: "Events",
    titleIt: "I nostri Eventi",
    titleEn: "Our Events",
    bodyIt: "Serate a tema, degustazioni, musica dal vivo e molto altro. Scopri il calendario degli eventi e vivi esperienze indimenticabili in un'atmosfera unica.",
    bodyEn: "Themed nights, tastings, live music and much more. Discover our events calendar and enjoy unforgettable experiences in a unique atmosphere.",
    ctaLabelIt: "Vedi gli eventi",
    ctaLabelEn: "See events",
    ctaHref: "/eventi",
    imageUrl: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    testId: "teaser-eventi",
  },
  {
    subtitleIt: "Eventi Privati",
    subtitleEn: "Private Events",
    titleIt: "Crea il tuo Evento",
    titleEn: "Create your Event",
    bodyIt: "Camera con Vista offre spazi esclusivi e servizi personalizzati per rendere ogni occasione indimenticabile. Dal party aziendale alla celebrazione privata, ogni dettaglio è curato con la massima attenzione.",
    bodyEn: "Camera con Vista offers exclusive spaces and personalized services to make every occasion unforgettable. From corporate parties to private celebrations, every detail is curated with the utmost attention.",
    ctaLabelIt: "Crea il tuo evento",
    ctaLabelEn: "Create your event",
    ctaHref: "/eventi-privati",
    imageUrl: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    testId: "teaser-privati",
  },
];
