export const HOME_PAGE_ID = 1;

export const DEFAULT_BLOCKS = {
  hero: {
    blockType: "hero",
    sortOrder: 0,
    titleIt: "Camera con Vista",
    titleEn: "Camera con Vista",
    bodyIt: "Ristorante & Cocktail Bar",
    bodyEn: "Restaurant & Cocktail Bar",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    imageScaleDesktop: 100,
    imageScaleMobile: 100,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageOffsetXMobile: 0,
    imageOffsetYMobile: 0,
    titleFontSize: 72,
    titleFontSizeMobile: 40,
    bodyFontSize: 28,
    bodyFontSizeMobile: 20,
    isDraft: false,
  },
  concept: {
    blockType: "concept",
    sortOrder: 1,
    titleIt: "Il nostro concept",
    titleEn: "Our Concept",
    bodyIt: "Camera con Vista è riconosciuto come uno dei cocktail bar più rinomati di Bologna. La nostra filosofia si basa sulla qualità degli ingredienti, l'innovazione nelle tecniche e la passione per l'ospitalità.",
    bodyEn: "Camera con Vista is recognized as one of the most renowned cocktail bars in Bologna. Our philosophy is based on the quality of ingredients, innovation in techniques, and passion for hospitality.",
    titleFontSize: 36,
    titleFontSizeMobile: 28,
    bodyFontSize: 16,
    bodyFontSizeMobile: 14,
    isDraft: false,
  },
  branding: {
    blockType: "branding",
    sortOrder: 2,
    titleIt: "RESTAURANT & COCKTAIL BAR",
    titleEn: "RESTAURANT & COCKTAIL BAR",
    bodyIt: "French nuance, antique goods",
    bodyEn: "French nuance, antique goods",
    titleFontSize: 15,
    titleFontSizeMobile: 11,
    bodyFontSize: 26,
    bodyFontSizeMobile: 18,
    isDraft: false,
  },
};

export const TEASER_CARDS = [
  {
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    titleIt: "Cocktail Bar",
    titleEn: "Cocktail Bar",
    descriptionIt: "Cocktail creativi preparati con ingredienti di prima qualità",
    descriptionEn: "Creative cocktails prepared with premium ingredients",
    href: "/cocktail-bar",
    testId: "card-cocktail",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    titleIt: "Ristorante",
    titleEn: "Restaurant",
    descriptionIt: "Cucina raffinata con prodotti locali e stagionali",
    descriptionEn: "Refined cuisine with local and seasonal products",
    href: "/menu",
    testId: "card-restaurant",
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    titleIt: "Eventi Privati",
    titleEn: "Private Events",
    descriptionIt: "Spazi esclusivi per le tue occasioni speciali",
    descriptionEn: "Exclusive spaces for your special occasions",
    href: "/eventi-privati",
    testId: "card-events",
  },
];
